# numpy 套件


In [1]:
a_list=[5,4,3,2,1]
print(a_list*3)

[5, 4, 3, 2, 1, 5, 4, 3, 2, 1, 5, 4, 3, 2, 1]


In [4]:
#numpy套件的ndarray型態，提供element-wise的操作
import numpy as np
a_ndarray=np.array([5,4,3,2,1])
print(a_ndarray*3)

[15 12  9  6  3]


In [3]:
print(type(a_ndarray))
print(a_ndarray.ndim) 
print(a_ndarray.shape) 
print(a_ndarray.dtype) 

<class 'numpy.ndarray'>
1
(5,)
int32


In [6]:
print(np.zeros(6)) 
print(np.zeros((2, 6)))
print(np.empty((2, 6, 2))) 
print(np.arange(16))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.33511018e-306]
  [6.23057689e-307 7.56602524e-307]
  [8.45559303e-307 8.06612616e-308]
  [6.89810244e-307 1.22387550e-307]
  [2.22522596e-306 8.34423917e-308]
  [1.11261162e-306 1.78021527e-306]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# ndarray的進階操作

In [7]:
my_array = np.arange(11)
print(my_array)
print(my_array[0])
print(my_array[0:5]) 

[ 0  1  2  3  4  5  6  7  8  9 10]
0
[0 1 2 3 4]


In [6]:
#二維ndarray取值
my_2d_array = np.array([np.arange(0, 5), np.arange(5, 10)])
print(my_2d_array)
print(my_2d_array[1, :]) 
print(my_2d_array[:, 1]) 
print(my_2d_array[1, 1]) 


[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [8]:
#假設有六個組別"Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"，
#其參加人數分別為56, 8, 19, 14, 6, 71人
ironmen = [56, 8, 19, 14, 6, 71]
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_array = np.array(ironmen)
groups_array = np.array(groups)
print(ironmen_array)
print(groups_array)

[56  8 19 14  6 71]
['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']


In [9]:
# 用人數去篩選組別
print(ironmen_array >= 10) # 布林值陣列
print(groups_array[ironmen_array >= 10]) # 鐵人數大於 10 的組別
# 用組別去篩選人數
print(groups_array != "自我挑戰組") 
print(ironmen_array[groups_array != "自我挑戰組"]) 

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray轉置

In [13]:
my_1d_array = np.arange(10)
print(my_1d_array)
my_2d_array = my_1d_array.reshape((2, 5)) 
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [16]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
# ndarray nan(空值) 與 inf(無窮大)

In [13]:
nan_array = np.array([56, 8, 19, 14, 6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


In [14]:
normal_samples = np.random.normal(size = 10) 

uniform_samples = np.random.uniform(size = 10) 

print(normal_samples)
print("---") # 分隔線
print(uniform_samples)

[-0.27150656  0.61719641  0.32323131  1.52432155  0.82467068  0.84755358
  0.7002174  -0.85964107 -0.99196632 -0.76966889]
---
[0.06809563 0.59788224 0.10759276 0.21389078 0.44115933 0.73207047
 0.7536309  0.09071146 0.5466007  0.37204746]
